# Generated by Django 3.1 on 2020-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(max_length=2000),
        ),
    ]
