# Generated by Django 3.1 on 2020-08-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_auto_20200809_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='1', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.TextField(default='1', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='certify',
            field=models.TextField(default='1', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(default='1', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.TextField(default='1', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='1', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='oskills',
            field=models.CharField(default='1', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(default='1', max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sgrade',
            field=models.CharField(default='1', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skills2',
            field=models.CharField(default='1', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skills3',
            field=models.CharField(default='1', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ugrade',
            field=models.CharField(default='1', max_length=2000),
            preserve_default=False,
        ),
    ]
