# Generated by Django 3.1 on 2020-08-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_auto_20200809_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
